###
### 게시판 목록

GET http://laravel.homestead.test/api/v1/boards
Content-Type: application/json
Authorization: Bearer gssVe10Z1qyfYgs32apbVVaJXlv1VMZltpmGpMYHVSwMfN0hftW4KHouXtmC

{
    "page": 1,
    "per_page": 30,
    "bbs_type": 2
}


###
### 게시글 보기
GET http://laravel.homestead.test/api/v1/boards/112
Content-Type: application/json
Authorization: Bearer gssVe10Z1qyfYgs32apbVVaJXlv1VMZltpmGpMYHVSwMfN0hftW4KHouXtmC

###
### 게시글 작성
POST http://laravel.homestead.test/api/v1/boards
Content-Type: application/json
Authorization: Bearer gssVe10Z1qyfYgs32apbVVaJXlv1VMZltpmGpMYHVSwMfN0hftW4KHouXtmC

{
    "bbs_type": 1,
    "title": "My Father Goes To The Market With Donkey...",
    "body": "Horore Choo Choo Parero~"
}

###
### 게시글 수정
PUT http://laravel.homestead.test/api/v1/boards/100
Content-Type: application/json
Authorization: Bearer gssVe10Z1qyfYgs32apbVVaJXlv1VMZltpmGpMYHVSwMfN0hftW4KHouXtmC

{
    "title": "안녕하세요. 하하하하하",
    "body": "라라벨 이제는 좀 쉽다."
}

###
### 게시글 삭제
DELETE http://laravel.homestead.test/api/v1/boards/57
Content-Type: application/json
Authorization: Bearer gssVe10Z1qyfYgs32apbVVaJXlv1VMZltpmGpMYHVSwMfN0hftW4KHouXtmC

###
### banners
GET http://laravel.homestead.test/api/v1/banners
Content-Type: application/json
Authorization: Bearer gssVe10Z1qyfYgs32apbVVaJXlv1VMZltpmGpMYHVSwMfN0hftW4KHouXtmC

{
    "page": 1,
    "per_page": 20,
    "category_id": 1,
    "sub_category_id": 2
}


##
### comment

POST http://laravel.homestead.test/api/v1/boards/86/comment
Content-Type: application/json
Authorization: Bearer gssVe10Z1qyfYgs32apbVVaJXlv1VMZltpmGpMYHVSwMfN0hftW4KHouXtmC

{
    "body": "아버지는 나귀타고 장에 가시고...할머니는 건너마을 아저씨 댁에.."
}


### user

GET http://laravel.homestead.test/api/user
Content-Type: application/json
Authorization: Bearer gssVe10Z1qyfYgs32apbVVaJXlv1VMZltpmGpMYHVSwMfN0hftW4KHouXtmC
