###
### 게시판 목록
GET http://laravel.homestead.test/api/v1/boards HTTP/1.1
Content-Type: application/json

{
    "page": 1,
    "per_page": 30,
    "bbs_type": 2
}


###
### 게시글 보기
GET http://laravel.homestead.test/api/v1/boards/58 HTTP/1.1
Content-Type: application/json

###
### 게시글 작성
POST http://laravel.homestead.test/api/v1/boards HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "title": "My Father Goes To The Market With Donkey...",
    "body": "Horore Choo Choo Parero~"
}

###
### 게시글 수정
PUT http://laravel.homestead.test/api/v1/boards/100 HTTP/1.1
Content-Type: application/json

{
    "title": "안녕하세요. 하하하하하",
    "body": "라라벨 이제는 좀 쉽다."
}

###
### 게시글 삭제
DELETE http://laravel.homestead.test/api/v1/boards/57 HTTP/1.1


###
### banners
GET http://laravel.homestead.test/api/v1/banners
Content-Type: application/json

{
    "page": 1,
    "per_page": 20,
    "category_id": 1,
    "sub_category_id": 2
}